### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mercenaruss**
- Update description
- Added link to documentation

### CODE REVIEW

**Comment by xyzroe** [comment]
links have the same meaning. no need to repeat twice

**Comment by mercenaruss** [comment]
actually second link is for website. Not updating GitHub directory or keep documentation on Github.

**Comment by xyzroe** [comment]
But your repository starts with a link to the site? right in the title. 
GitHub is not an advertising platform, the link to the repository seems to me to be enough.

**Comment by mercenaruss** [comment]
okay,let keep this way

**Pull request closed without merging**
